### ISSUE TITLE
www.ruggedsoftware.org doesn't work

### ISSUE THREAD

**Issue by MrSeccubus** [planetlevel/rugged-software#2]
It is in the tag line of your GitHub project, but it doesn't work :(
ruggedsoftware.org does work.

**Comment by JonathanMcCormickJr** [comment]
I can confirm this. 

The **ruggedsoftware.org** domain loads the webpage fine: 
![image](https://github.com/user-attachments/assets/58b86976-c725-473a-adba-98ed62191452)

...but the **www**.ruggedsoftware.org subdomain does not seem to actually load: 
![image](https://github.com/user-attachments/assets/24241414-8fe1-42b4-9b5a-cc7f1dc2c5e7)

**Comment by planetlevel** [comment]
Fixed tagline.

**Comment by MrSeccubus** [comment]
Wouldn;t it have been better to fix the DNS record for www.ruggedsoftware.org and add that domain to the `CNAME` file too? Now you are sending users who happen to type www in front of the domain to something in Amazon.

**Comment by planetlevel** [comment]
Fixed this too and turned on enforce SSL.  Sorry for delay, had to add DNS TXT record to allow Github to verify domain.  Let me know if you have any issues.

**Comment by MrSeccubus** [comment]
It works, thanks.

Sent from my mobile device, sorry for the typyos.

On 4 Dec 2024, at 14:19, Jeff Williams ***@***.***> wrote:

﻿

Fixed this too and turned on enforce SSL. Sorry for delay, had to add DNS TXT record to allow Github to verify domain. Let me know if you have any issues.
